volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_django_media: {}
  
  production_redis_data: {}
  
networks:
  survey_network:
    name: survey_network
  swag_network:
    name: swag_network
    external: true
  default:
    name: survey_network

services:
  djangosurvey: &django
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: mind_survey_app_production_django
    volumes:
      - production_django_media:/app/mind_survey_app/media
    networks:
      - survey_network
      - swag_network
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: mind_survey_app_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/18/docker
      - /var/sites/surveys/backups:/backups
      #- production_postgres_data_backups:/backups
    networks:
      survey_network:
    env_file:
      - ./.envs/.production/.postgres

  redis:
    restart: always
    image: docker.io/redis:8.6
    volumes:
      - production_redis_data:/data
    networks:
      survey_network:

  celeryworker:
    <<: *django
    image: mind_survey_app_production_celeryworker
    command: /start-celeryworker
    networks:
      survey_network:

  celerybeat:
    <<: *django
    image: mind_survey_app_production_celerybeat
    command: /start-celerybeat
    networks:
      survey_network:

  flower:
    <<: *django
    image: mind_survey_app_production_flower
    command: /start-flower
    networks:
      survey_network:

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: mind_survey_app_production_nginx
    depends_on:
      - djangosurvey
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    networks:
      survey_network:

